<a href="https://colab.research.google.com/github/yongzhiqu/IE_4495/blob/master/mandatory_homework_for_low_quiz_score.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
# python practice

# 1. you are given a list of numbers, could you write a function to find whether a number appeared in the list:
# for example given [1,2,4,7,9.5,10], could you determin whether 3 is in the list or not
# If yes, return true, if not return false
# PLEASE FILL IN THE FOLLOWING FUNCTION TO ACCOMPLISH THE TASK
# think about what should you inputs be, what is your outputs
# your function should be able to take in a list and a nubmer and compare each element of list to the number
def find_number( , ):
# you may need a for loop to check each element of the list




In [ ]:
# 2. Same as problem one, could you write a program to count the number of time an number appeared in a list
# for example given [1, 2, 3, 2, 2, 3, 4, 5, 6, 8], if you are asked to check home many times 2 appears
# your output should be 3, because 2 appears 3 times.
def count_time( , ):

In [ ]:
# 3. Could you wrtie a function to compute the average absolute difference of two matrices of the same size
# for example Matrix A = [[1,2],[2,3]], B = [[1,3],[1,4]]
# you should get avergae(A-B) = (0 + abs(-1) + 1 + abs(-1))/4
# you are given A1 = [[1,2],[2,3], [1,5]], B1 = [[1,3],[1,4],[2,3]]
# you should get average(A1-B1) = (0 + abs(-1) + 1 + abs(-1) + abs(-1) + 2)/6
# hint: you could use abs(A-B) for matrix you can also do sum(abs(A-B)) directly without using for loop.
def average_diff (A, B):
    # your program start here:



In [ ]:
# 4. could wrtie a fucntion solver for a * X^2 + b * X + c = d
# you are given the following function definition
def sovle_quadratic_function(a, b, c, d):
    # you program start here:
    # please use the normal formular: x1 = (-b + sqrt(b^2 - 4*a*c))/2*a; x2 = (-b - sqrt(b^2 - 4*a*c))/2*a

In [ ]:
# 5. Write a Python program to remove and print every second number from a list of numbers and return the remaining list

# for example if you are given a list [1,2,3,4,5,6,7]
# you should print 2,4,6, and return [1,3,5,7]
def print_delete_everysecondnumber( listA ):
    



In [14]:
# 6. Use my posted midterm solutions (or the neural network program in quiz 1, they are the same)
# to crate and training a neural network for the following dataset X and Y
# Where each element in the X is the input and each element in the Y is the output label.
# Basically, you have 7 X[i]'s and 7 Y[i]'s. 
# ex. [0.7, 0.6, 0.8, 0.1, 0.2, 0.3] has a Y label of [0.9,0.1]
# [0.2, 0.3, 0.46, 0.6, 0.65, 0.74] has a Y label of [0.1 0.9]
# You do not need to wrtie a homework, you need to call the neural network function to do the training task

X = np.array([[0.7, 0.6, 0.8, 0.1, 0.2, 0.3], [0.55, 0.8, 0.6, 0.3, 0.03, 0.4], 
              [0.59, 0.75, 0.64, 0.12, 0.07, 0.1], [0.59, 0.75, 0.64, 0.12, 0.07, 0.1],
              [0.2, 0.3, 0.46, 0.6, 0.65, 0.74], [0.25, 0.45, 0.38, 0.9, 0.88, 0.72], 
              [0.39, 0.42, 0.21, 0.58, 0.95, 0.67]])
              
Y = np.array([[0.9,0.1],[0.9,0.1],[0.9,0.1],[0.9,0.1], [0.1,0.9], [0.1,0.9], [0.1,0.9]])
print(X)
print(Y)

# please create a neural network and train your neural network
# your code start here:


# could you use your train neural network to test the ouput of [0.65, 0.45, 0.2, 0.86, 0.45, 0.94]
# What is the predicted label?
# could you predict [0.11, 0.22, 0.17, 0.92, 0.55, 0.77]?

# your prediction code goes here:


[[0.7  0.6  0.8  0.1  0.2  0.3 ]
 [0.55 0.8  0.6  0.3  0.03 0.4 ]
 [0.59 0.75 0.64 0.12 0.07 0.1 ]
 [0.59 0.75 0.64 0.12 0.07 0.1 ]
 [0.2  0.3  0.46 0.6  0.65 0.74]
 [0.25 0.45 0.38 0.9  0.88 0.72]
 [0.39 0.42 0.21 0.58 0.95 0.67]]
[[0.9 0.1]
 [0.9 0.1]
 [0.9 0.1]
 [0.9 0.1]
 [0.1 0.9]
 [0.1 0.9]
 [0.1 0.9]]
