<a href="https://colab.research.google.com/github/yongzhiqu/IE_4495/blob/master/NeuralNets_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# implementation of a neural network
import numpy as np

In [4]:
def generateNeuralNet(shape):
    neuralNet = []
    for i in range(len(shape)-1):
        #neuralNet.append(np.random.random((shape[i+1],shape[i])))
        neuralNet.append(np.random.random((shape[i+1],shape[i]+1))*2-1)
    return neuralNet

In [5]:
# now do feedforward for the neural network we just created
def applyneuralNet(neuralNet, input):
    values = []
    values.append(input)
    for i in range(len(neuralNet)):
        z = neuralNet[i]@np.append(values[i],1)
        activation = 1/(1 + np.exp(-z)) 
        values.append(activation)
    return values

In [6]:
# test function generateNeuralNet()
my_net = generateNeuralNet([10,5,2])
print(my_net)
for l in my_net:
    print(l.shape)

[array([[-0.81715282, -0.19414484, -0.33444855,  0.26114953,  0.39702071,
         0.16951564, -0.89077598,  0.9018282 ,  0.71029143, -0.47348378,
         0.00695593],
       [-0.87082056, -0.96894715, -0.6768571 ,  0.86556543, -0.47970267,
        -0.03958634,  0.73130572,  0.35223209, -0.75141061, -0.91521701,
         0.90831749],
       [-0.670493  , -0.55421556, -0.99759919, -0.69901391, -0.7311542 ,
        -0.22856194, -0.9657784 ,  0.26745805, -0.2157682 ,  0.89445625,
         0.26344682],
       [ 0.50489291, -0.38444158, -0.35494042, -0.42812728, -0.56018922,
         0.21238176, -0.50586192, -0.5406602 ,  0.70590456, -0.69434625,
        -0.89026392],
       [ 0.28580799, -0.28182055, -0.45147803,  0.63721424,  0.98268415,
         0.60728175,  0.64251514, -0.51893801, -0.96484284,  0.12410752,
        -0.54984297]]), array([[-0.07846743, -0.18838548,  0.18007236, -0.24682982,  0.25516671,
         0.98298535],
       [-0.97039432,  0.76593118,  0.17023792,  0.52891925,  0

In [7]:
# test feedforward for neural network

my_shape = [10,6,3,10]
my_net = generateNeuralNet(my_shape)

In [8]:
import random
test_input = np.array([random.randrange(0, 9) for p in range(0, 10)])

In [9]:
my_networks_value = applyneuralNet(my_net, test_input)
print(my_networks_value)
for l in my_networks_value:
    print(l.shape)


[array([4, 8, 4, 8, 8, 0, 4, 5, 6, 4]), array([9.94338753e-01, 9.15775565e-01, 4.98514242e-01, 2.66245113e-04,
       8.23769494e-01, 9.97870637e-01]), array([0.49495048, 0.30590355, 0.81675103]), array([0.67781741, 0.70409654, 0.35961607, 0.62069646, 0.6404335 ,
       0.365081  , 0.43219048, 0.71412071, 0.38390456, 0.25946451])]
(10,)
(6,)
(3,)
(10,)


In [10]:
def trainNeuralNet(neuralNet, input, output, iterations):
    learningrate = 0.008
    theta = 10e-4
    total_error = np.inf

    for i in range(iterations):

        if total_error < theta:
           break

        values = applyneuralNet(neuralNet, input)
        total_error = np.mean(np.abs(values[-1] - output))
        error = values[-1] - output

        # if i % 500 == 0:
        #     print('total_error at', i, ' = ',  total_error)

        for j in range(len(neuralNet)-1,-1,-1):
            layerout = values[j+1]
            layerin = values[j]
            delta = (layerout * (1 - layerout)) * error

            error = np.dot((neuralNet[j][:,:-1]).transpose(), delta)

            neuralNet[j][:,:-1] = neuralNet[j][:,:-1] - learningrate * np.dot(np.transpose([delta]),[layerin],) # r by 1 * 1 * k = r*k
            neuralNet[j][:,-1] = neuralNet[j][:,-1] - (learningrate * delta).transpose()

    return neuralNet




In [11]:
my_shape = [100,50,10,3]
my_net = generateNeuralNet(my_shape)
test_input = np.array([random.randrange(0, 9) for p in range(0, 100)])
test_out = np.array([0.05,0.3,0.95])


In [12]:
print(my_net[-1])
my_trained_Net = trainNeuralNet(my_net, test_input, test_out, 100)

my_value = applyneuralNet(my_trained_Net, test_input)
print(my_value[-1])

[[ 0.46929254  0.12870859 -0.41591874  0.85582014 -0.35375352 -0.70033861
  -0.57204353  0.71810853 -0.63305964  0.74508532  0.10284406]
 [-0.94008895  0.49955218  0.7729905  -0.50137184  0.17769997 -0.98599467
  -0.41874059  0.45566787  0.98618506 -0.1831211  -0.41337083]
 [-0.30875277 -0.00281609 -0.64949511  0.087245    0.7847402   0.68169621
  -0.24488417  0.70786461  0.5600192  -0.88803112 -0.09444948]]
[0.23279526 0.36987757 0.76814555]


In [13]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import os
from matplotlib import pyplot as plt

mnist = tf.keras.datasets.mnist

(training_images, training_labels), (test_images, test_labels) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [23]:
N=60000
trainingData_N = training_images[:N]
traininglabel_N = training_labels[:N]

In [24]:
def normalize(data):
    return (data-np.min(data))/(np.max(data)-np.min(data))

In [26]:
from keras.utils import to_categorical
trainingData_N = trainingData_N.reshape(N,784)
#traininglabel_N = traininglabel_2000/10.0
trainingData_N = normalize(trainingData_N)

from keras.utils import to_categorical
print(traininglabel_N[:10])
traininglabel_N_cat = to_categorical(traininglabel_N)

n=2000
testing_imageN = training_images[10000:10000+n]
testing_imageN = normalize(testing_imageN)
testing_imageN = testing_imageN.reshape(n,784)
testing_labelN = training_labels[10000:10000+n]
testing_labelN_cat = to_categorical(testing_labelN)

for i in range (10):
    print(np.argmax(traininglabel_N_cat[i]))


[5 0 4 1 9 2 1 3 1 4]
5
0
4
1
9
2
1
3
1
4


In [29]:
my_shape = [784,128,50,10]
MNIST_net = generateNeuralNet(my_shape)
N=60000

print(traininglabel_N[:10])

epoch = 1
for k in range(epoch):
    for i in range(N):
        MNIST_net = trainNeuralNet(MNIST_net, trainingData_N[i], traininglabel_N_cat[i], 5)


[5 0 4 1 9 2 1 3 1 4]


In [36]:
n=20
pred_output = np.ones([n,10])

MNIST_value = []
for j in range(n):
    MNIST_value.append(applyneuralNet(MNIST_net, trainingData_N[j]))
    pred_output[j] = MNIST_value[j][-1]
    print('true label =', traininglabel_N[j])
    print('pred label =',np.argmax(np.round(pred_output[j])))



true label = 5
pred label = 5
true label = 0
pred label = 0
true label = 4
pred label = 4
true label = 1
pred label = 1
true label = 9
pred label = 9
true label = 2
pred label = 2
true label = 1
pred label = 1
true label = 3
pred label = 3
true label = 1
pred label = 1
true label = 4
pred label = 4
true label = 3
pred label = 3
true label = 5
pred label = 0
true label = 3
pred label = 3
true label = 6
pred label = 6
true label = 1
pred label = 1
true label = 7
pred label = 7
true label = 2
pred label = 2
true label = 8
pred label = 8
true label = 6
pred label = 6
true label = 9
pred label = 9


In [37]:
n=2000
pred_output = np.ones([n,10])
MNIST_value = []
for j in range(n):
    MNIST_value.append(applyneuralNet(MNIST_net, testing_imageN[j]))
    pred_output[j] = MNIST_value[j][-1]

print(np.round(pred_output))

pred_output = np.round(pred_output)
error = pred_output - testing_labelN_cat

# print(error[:10])
j=0
for i in range(2000):
    if np.sum(np.abs(error[i]))>0:
       j=j+1
print(j/n)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
0.1475


In [47]:
my_shape = [784,128,10]
MNIST_net2 = generateNeuralNet(my_shape)
N=5000

print(traininglabel_N[:20])

epoch = 3
for k in range(epoch):
    for i in range(N):
        MNIST_net2 = trainNeuralNet(MNIST_net2, trainingData_N[i], traininglabel_N_cat[i], 10)

[5 0 4 1 9 2 1 3 1 4 3 5 3 6 1 7 2 8 6 9]


In [48]:
n=50
pred_output = np.ones([n,10])

MNIST_value = []
for j in range(n):
    MNIST_value.append(applyneuralNet(MNIST_net2, trainingData_N[j]))
    pred_output[j] = MNIST_value[j][-1]
    print('true label =', traininglabel_N[j])
    print('pred label =',np.argmax(np.round(pred_output[j])))

true label = 5
pred label = 0
true label = 0
pred label = 0
true label = 4
pred label = 4
true label = 1
pred label = 1
true label = 9
pred label = 9
true label = 2
pred label = 2
true label = 1
pred label = 1
true label = 3
pred label = 3
true label = 1
pred label = 1
true label = 4
pred label = 4
true label = 3
pred label = 3
true label = 5
pred label = 5
true label = 3
pred label = 3
true label = 6
pred label = 6
true label = 1
pred label = 1
true label = 7
pred label = 7
true label = 2
pred label = 2
true label = 8
pred label = 8
true label = 6
pred label = 0
true label = 9
pred label = 0
true label = 4
pred label = 4
true label = 0
pred label = 0
true label = 9
pred label = 0
true label = 1
pred label = 1
true label = 1
pred label = 0
true label = 2
pred label = 0
true label = 4
pred label = 4
true label = 3
pred label = 3
true label = 2
pred label = 0
true label = 7
pred label = 0
true label = 3
pred label = 0
true label = 8
pred label = 8
true label = 6
pred label = 6
true label

In [52]:
n=2000
pred_output = np.ones([n,10])
MNIST_value = []
for j in range(n):
    MNIST_value.append(applyneuralNet(MNIST_net2, testing_imageN[j]))
    pred_output[j] = MNIST_value[j][-1]

print(np.round(pred_output))

pred_output = np.round(pred_output)
error = pred_output - testing_labelN_cat[:n]

# print(error[:10])
j=0
for i in range(2000):
    if np.sum(np.abs(error[i]))>0:
       j=j+1
print(j/n)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
0.2605
