<a href="https://colab.research.google.com/github/yongzhiqu/IE_4495/blob/master/NeuralNets_part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# implementation of a neural network
import numpy as np

In [3]:
def generateNeuralNet(shape):
    neuralNet = []
    for i in range(len(shape)-1):
        #neuralNet.append(np.random.random((shape[i+1],shape[i]))) initialize between 0 - 1
        neuralNet.append(np.random.random((shape[i+1],shape[i]+1))*2-1)
    return neuralNet

In [47]:
# now do feedforward for the neural network we just created
def applyneuralNet(neuralNet, input):
    values = []
    values.append(input)
    for i in range(len(neuralNet)):
        z = neuralNet[i]@np.append(values[i],1)
        activation = 1/(1 + np.exp(-z)) 
        values.append(activation)
    return values

In [48]:
# test function generateNeuralNet()
my_net = generateNeuralNet([10,5,2])
print(my_net)

[array([[ 0.60740325, -0.61473441, -0.82557191,  0.40975048, -0.83015878,
         0.8864115 ,  0.60400729, -0.21453435, -0.73529863,  0.2584547 ,
         0.66596494],
       [ 0.27088473, -0.35856026, -0.24158018, -0.65544124,  0.25653692,
        -0.92987353,  0.73735635, -0.04093983,  0.0157272 ,  0.24499819,
         0.81902698],
       [ 0.17302882,  0.54888834, -0.90139876,  0.17635721, -0.45126817,
         0.24230493,  0.01882814, -0.16340277,  0.04419074, -0.76055253,
         0.74863254],
       [-0.36757906,  0.61680192,  0.76042425, -0.59137995,  0.63564455,
         0.87182183, -0.37052683,  0.22148705,  0.4393365 , -0.82228557,
         0.63008046],
       [ 0.9334757 , -0.95972511,  0.59650041, -0.63340889,  0.98891591,
        -0.2707814 , -0.09746974, -0.3051103 , -0.32623537, -0.98637947,
         0.57700611]]), array([[ 0.49004577,  0.78013212,  0.42085048,  0.81877087, -0.48469978,
        -0.57712715],
       [ 0.11893337,  0.12717976, -0.44152951,  0.08514797, -0

In [57]:
# this is only showing you how the applyneuralNet() function works step in step internally

import random
my_net_test = generateNeuralNet([10,6,3,1])

test_input = np.array([random.randrange(0, 9) for p in range(0, 10)])
print(test_input)
test_input = np.array(test_input)
z1 = my_net_test[0]@np.append(test_input,1)
layer1 = 1/(1 + np.exp(-z1)) 
z2 = my_net_test[1]@np.append(layer1,1)
layer2 = 1/(1 + np.exp(-z2)) 
z3 = my_net_test[2]@np.append(layer2,1)
layer3 = 1/(1 + np.exp(-z3)) 
print(z1)
print(layer1)
print(z2)
print(layer2)
print(z3)
print(layer3)

[0 1 3 8 3 0 1 2 4 1]
[-12.95965731  -4.23989821  -8.93943947   5.52270172   2.4828987
  -1.09188816]
[2.35337601e-06 1.42043866e-02 1.31097325e-04 9.96020857e-01
 9.22934226e-01 2.51262892e-01]
[ 0.44581504  0.17430603 -0.08068878]
[0.60964376 0.54346651 0.47983874]
[-0.60730717]
[0.35267371]


In [50]:
# test feedforward for neural network

my_shape = [10,6,4,3,10]
my_net = generateNeuralNet(my_shape)

In [51]:
test_input = np.array([random.randrange(0, 9) for p in range(0, 10)])

In [56]:
my_networks_value = applyneuralNet(my_net, test_input)
print(my_networks_value)

[array([0, 1, 2, 5, 8, 3, 4, 5, 7, 2]), array([9.99999998e-01, 2.92525009e-05, 7.45664936e-01, 6.44880002e-03,
       7.36231016e-03, 9.96157396e-01]), array([0.29817217, 0.16908022, 0.5440601 , 0.7889794 ]), array([0.38928653, 0.5795319 , 0.6212031 ]), array([0.71524129, 0.46784546, 0.56675524, 0.52088482, 0.53990595,
       0.26844932, 0.24469438, 0.72610833, 0.33712138, 0.34657764])]
