<a href="https://colab.research.google.com/github/yongzhiqu/IE_4495/blob/master/NeuralNets_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# implementation of a neural network
import numpy as np

In [ ]:
def generateNeuralNet(shape):
    neuralNet = []
    for i in range(len(shape)-1):
        #neuralNet.append(np.random.random((shape[i+1],shape[i])))
        neuralNet.append(np.random.random((shape[i+1],shape[i]+1))*2-1)
    return neuralNet

In [ ]:
# now do feedforward for the neural network we just created
def applyneuralNet(neuralNet, input):
    values = []
    values.append(input)
    for i in range(len(neuralNet)):
        z = neuralNet[i]@np.append(values[i],1)
        activation = 1/(1 + np.exp(-z)) 
        values.append(activation)
    return values

In [ ]:
# test function generateNeuralNet()
my_net = generateNeuralNet([10,5,2])
print(my_net)
for l in my_net:
    print(l.shape)

[array([[-0.32154236, -0.45519893, -0.05429296, -0.09670735,  0.29635526,
        -0.06146309, -0.11826986, -0.653065  , -0.01030405, -0.55065741,
         0.92007818],
       [-0.48730175, -0.18584659,  0.27479702,  0.65062861, -0.47558274,
         0.35987466,  0.17053307,  0.56535568, -0.19743629, -0.24391878,
         0.82995726],
       [-0.87772491,  0.413441  ,  0.32191768,  0.04904481,  0.55272443,
         0.90334426,  0.39606199,  0.77657655,  0.02235523, -0.9874387 ,
        -0.99595318],
       [ 0.52823493,  0.51617766, -0.00330487,  0.2226916 ,  0.46341701,
         0.24579342, -0.50826274,  0.58854999,  0.24105374,  0.27418079,
         0.18098135],
       [-0.25393254,  0.16368403, -0.00306888, -0.56129922, -0.29750659,
         0.80752367,  0.80793826, -0.77636417, -0.58393246,  0.17169916,
        -0.75991965]]), array([[ 0.48699387,  0.84477231,  0.72844823,  0.83397598, -0.46959895,
        -0.95834555],
       [ 0.72440178, -0.63488553,  0.3799339 ,  0.94866791, -0

In [ ]:
# test feedforward for neural network

my_shape = [10,6,3,10]
my_net = generateNeuralNet(my_shape)

In [ ]:
import random
test_input = np.array([random.randrange(0, 9) for p in range(0, 10)])

In [ ]:
my_networks_value = applyneuralNet(my_net, test_input)
print(my_networks_value)
for l in my_networks_value:
    print(l.shape)


[array([7, 0, 1, 2, 8, 1, 6, 6, 4, 4]), array([6.13332000e-02, 4.65083973e-01, 4.08838380e-04, 9.91120293e-01,
       4.56510297e-03, 5.08116316e-04]), array([0.14428474, 0.20000254, 0.57049631]), array([0.42248359, 0.4812433 , 0.54193189, 0.66147514, 0.38356025,
       0.56749419, 0.46811888, 0.29505691, 0.55109389, 0.45551387])]
(10,)
(6,)
(3,)
(10,)


In [ ]:
def trainNeuralNet(neuralNet, input, output, iterations):
    learningrate = 0.008
    theta = 10e-4
    total_error = np.inf

    for i in range(iterations):

        if total_error < theta:
           break

        values = applyneuralNet(neuralNet, input)
        total_error = np.mean(np.abs(values[-1] - output))
        error = values[-1] - output

        # if i % 500 == 0:
        #     print('total_error at', i, ' = ',  total_error)

        for j in range(len(neuralNet)-1,-1,-1):
            layerout = values[j+1]
            layerin = values[j]
            delta = (layerout * (1 - layerout)) * error

            error = np.dot((neuralNet[j][:,:-1]).transpose(), delta)

            neuralNet[j][:,:-1] = neuralNet[j][:,:-1] - learningrate * np.dot(np.transpose([delta]),[layerin],) # r by 1 * 1 * k = r*k
            neuralNet[j][:,-1] = neuralNet[j][:,-1] - (learningrate * delta).transpose()

    return neuralNet




In [ ]:
my_shape = [100,50,10,3]
my_net = generateNeuralNet(my_shape)
test_input = np.array([random.randrange(0, 9) for p in range(0, 100)])
test_out = np.array([0.05,0.3,0.95])


In [ ]:
print(my_net[-1])
my_trained_Net = trainNeuralNet(my_net, test_input, test_out, 100)

my_value = applyneuralNet(my_trained_Net, test_input)
print(my_value[-1])

[[ 0.74557046 -0.8091749   0.48336699 -0.41692392 -0.84012132 -0.35870464
  -0.1023443   0.32118274  0.23791565 -0.83343113 -0.98306422]
 [-0.38404455 -0.40813912 -0.4002646   0.20570808  0.18246724  0.46357878
   0.52704103 -0.62349834 -0.97231552  0.33248255 -0.38057414]
 [-0.75976102  0.08991428  0.15631126  0.12441183 -0.215036    0.41108439
   0.42065943  0.83379689  0.8908808  -0.5907541   0.33182337]]
[0.09351337 0.29753533 0.83565492]


In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import os
from matplotlib import pyplot as plt

mnist = tf.keras.datasets.mnist

(training_images, training_labels), (test_images, test_labels) = mnist.load_data()

In [ ]:
N=60000
trainingData_N = training_images[:N]
traininglabel_N = training_labels[:N]

In [ ]:
def normalize(data):
    return (data-np.min(data))/(np.max(data)-np.min(data))

In [ ]:
from keras.utils import to_categorical
trainingData_N = trainingData_N.reshape(N,784)
#traininglabel_N = traininglabel_2000/10.0
trainingData_N = normalize(trainingData_N)

from keras.utils import to_categorical
print(traininglabel_N)
traininglabel_N = to_categorical(traininglabel_N)

n=2000
testing_imageN = training_images[10000:10000+n]
testing_imageN = normalize(testing_imageN)
testing_imageN = testing_imageN.reshape(n,784)
testing_labelN = training_labels[10000:10000+n]
testing_labelN = to_categorical(testing_labelN)

print(traininglabel_N[:10])

[5 0 4 ... 5 6 8]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [ ]:
my_shape = [784,128,50,10]
MNIST_net = generateNeuralNet(my_shape)
N=60000

print(traininglabel_N[:50000])

epoch = 1
for k in range(epoch):
    for i in range(N):
        MNIST_net = trainNeuralNet(MNIST_net, trainingData_N[i], traininglabel_N[i], 5)


[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [ ]:
n=50
pred_output = np.ones([n,10])

MNIST_value = []
for j in range(n):
    MNIST_value.append(applyneuralNet(MNIST_net, trainingData_N[j]))
    pred_output[j] = MNIST_value[j][-1]

print(traininglabel_N[:20])
print(np.round(pred_output))

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0

In [ ]:
n=2000
pred_output = np.ones([n,10])
MNIST_value = []
for j in range(n):
    MNIST_value.append(applyneuralNet(MNIST_net, testing_imageN[j]))
    pred_output[j] = MNIST_value[j][-1]

print(np.round(pred_output))

pred_output = np.round(pred_output)
error = pred_output - testing_labelN

print(error[:100])
j=0
for i in range(2000):
    if np.sum(np.abs(error[i]))>0:
       j=j+1
print(j/n)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  

In [ ]:
my_shape = [784,128,10]
MNIST_net2 = generateNeuralNet(my_shape)
N=5000

print(traininglabel_N[:20])

epoch = 5
for k in range(epoch):
    for i in range(N):
        MNIST_net = trainNeuralNet(MNIST_net2, trainingData_N[i], traininglabel_N[i], 10)

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
n=50
pred_output = np.ones([n,10])

MNIST_value = []
for j in range(n):
    MNIST_value.append(applyneuralNet(MNIST_net2, trainingData_N[j]))
    pred_output[j] = MNIST_value[j][-1]

print(traininglabel_N[:20])
print(np.round(pred_output))

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0

In [ ]:

pred_output = np.ones([n,10])
MNIST_value = []
for j in range(n):
    MNIST_value.append(applyneuralNet(MNIST_net2, testing_imageN[j]))
    pred_output[j] = MNIST_value[j][-1]

print(np.round(pred_output))

pred_output = np.round(pred_output)
error = pred_output - testing_labelN

print(error[:100])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  