In [ ]:
a = 3
b = 5
c = a + b
c
squares = [1, 4, 9, 16, 25]
squares



[1, 4, 9, 16, 25]

In [ ]:
squares = squares + [36, 49, 64, 81, 100]
squares

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
cubes = [1, 8, 27, 65, 125] 

In [ ]:
import numpy as np #Features
x = np.array([[2, 1834, 1],[3, 1534, 2],[2, 962, 3]])# Target or Price
y = [8500, 9600, 258800]
x

array([[   2, 1834,    1],
       [   3, 1534,    2],
       [   2,  962,    3]])

In [ ]:
A = [[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]]

print("A =", A) 
print("A[0] =", A[0])      # 2nd row
print("A[1][2] =", A[1][2])   # 3rd element of 2nd row
print("A[0][-2] =", A[0][-2])   # Last element of 1st Row

column = [];        # empty list
for row in A:
  column.append(row[2])   

print("3rd column =", column)

A = [[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]
A[0] = [1, 4, 5, 12]
A[1][2] = 9
A[0][-2] = 5
3rd column = [5, 9, 11]


In [ ]:
x = np.array([[1,2],[3,4]]) 
x.astype(float)
y = np.linalg.inv(x) 
y.astype(float)
print (x) 
print (y) 
print (x*y)
w=np.dot(x,y)
print(w)

print ('**********I am the separation line ************')
z = np.matmul(x,y)
print(z)




[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[-2.   2. ]
 [ 4.5 -2. ]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
**********I am the separation line ************
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [ ]:
x = np.arange(10)
print(x)
print (x[0])
print (x[5])

[0 1 2 3 4 5 6 7 8 9]
0
5


In [ ]:
A = [[1, 4, 5], [-5, 8, 9], [-6, 7, 11]]
A = np.array (A)
transpose_A = A.transpose()
transpose_A2 = np.transpose(A)

print (transpose_A)

print (transpose_A2)

[[ 1 -5 -6]
 [ 4  8  7]
 [ 5  9 11]]
[[ 1 -5 -6]
 [ 4  8  7]
 [ 5  9 11]]


In [ ]:
eig_A=np.linalg.eig(A)
eig_A

(array([13.59373746,  5.03209301,  1.37416954]),
 array([[ 0.45145779,  0.83661458,  0.10258363],
        [ 0.62348353,  0.44632316, -0.77299039],
        [ 0.63832135,  0.31760303,  0.62606905]]))